FROM python:3.12.12-slim
WORKDIR /app
COPY requirements.txt ./
COPY src/data ./src/data
COPY src/models ./src/models
COPY .git ./git
RUN apt-get update && apt-get install -y git && \
  rm -rf /var/lib/apt/lists/* && \
  pip install -r requirements.txt
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="${PYTHONPATH}:/app"
EXPOSE 8000
WORKDIR /app/src/models
CMD uvicorn weather_api:api --host 0.0.0.0 --port 8000
# WORKDIR /app
# CMD python src/tests/tests.py && tail -f /dev/null
