FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
COPY pyproject.toml uv.lock ./
COPY src ./src
COPY .git ./git
RUN apt-get update && apt-get install -y curl git && \
  curl -LsSf https://astral.sh/uv/install.sh | sh && \
  $HOME/.local/bin/uv sync && . .venv/bin/activate
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="${PYTHONPATH}:/app"
EXPOSE 8000
WORKDIR /app/src/models
CMD uvicorn weather_api:api --host 0.0.0.0 --port 8000
# WORKDIR /app
# CMD python src/tests/tests.py && tail -f /dev/null
