FROM python:3.12.12-slim
WORKDIR /app
COPY requirements.txt ./
COPY src/visualization/Streamlit.py ./src/visualization/Streamlit.py
# COPY data/raw/weatherAUS.csv ./data/raw/
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install -r requirements.txt
ENV PYTHONPATH="${PYTHONPATH}:/app"
EXPOSE 8501
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "src/visualization/Streamlit.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
