FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install cron and curl
RUN apt-get update && apt-get install -y cron curl

# Copy cron pipeline script and make it executable
COPY src/cron_pipeline.sh ./src/cron_pipeline.sh
RUN chmod +x ./src/cron_pipeline.sh

# Create necessary directories

# Defining the cron job and executing it every 10 minutes
RUN echo "*/10 * * * * root MODEL_URI=${MODEL_URI:-http://weather_model_container:8000} /app/src/cron_pipeline.sh" > /etc/cron.d/my-cron \
    && chmod 0644 /etc/cron.d/my-cron \
    && crontab /etc/cron.d/my-cron

CMD ["cron", "-f"]