FROM python:3.12.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
EXPOSE 8080
CMD mlflow server \
  --host 0.0.0.0 \
  --port 8080 \
  --allowed-hosts '*' \
  --cors-allowed-origins '*' \
  --backend-store-uri file:///app/models \
  --default-artifact-root file:///app/models \
  --serve-artifacts